### ISSUE TITLE
Unique constraint of multiple attributes

### ISSUE THREAD

**Issue by metathairs** [iermb/SIMBA3#13]
@jordillobet  https://github.com/iermb/SIMBA3/blob/5fd202e0cb264ecce431ff776b9646c8151b267a/code/SIMBA3/src/Api/Persistence/Migrations/Variable/Entity.TypeArea.orm.xml#L15

I found this specification for creating unique constraint. Though it seams working only for mongodb ODM implementation.

**Comment by jordillobet** [comment]
Fix, dql. Check this documentation for creating join's in DQL

**Comment by jordillobet** [comment]
Here the link https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/dql-doctrine-query-language.html#joins
